//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("Lab2_Purnyn")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("Lab2_Purnyn")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="Lab2_Purnyn.Y2014.M10, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bb4e192dd" +
    "4830018")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformLab2_Purnyn {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Lab2_Purnyn.Proxy.Lab2_PurnynState), new global::Microsoft.Dss.Core.Attributes.Transform(Lab2_Purnyn_Proxy_Lab2_PurnynState_TO_Lab2_Purnyn_Lab2_PurnynState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Lab2_Purnyn.Lab2_PurnynState), new global::Microsoft.Dss.Core.Attributes.Transform(Lab2_Purnyn_Lab2_PurnynState_TO_Lab2_Purnyn_Proxy_Lab2_PurnynState));
        }
        
        private static global::Lab2_Purnyn.Proxy.Lab2_PurnynState _cachedInstance0 = new global::Lab2_Purnyn.Proxy.Lab2_PurnynState();
        
        private static global::Lab2_Purnyn.Lab2_PurnynState _cachedInstance = new global::Lab2_Purnyn.Lab2_PurnynState();
        
        public static object Lab2_Purnyn_Proxy_Lab2_PurnynState_TO_Lab2_Purnyn_Lab2_PurnynState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Lab2_Purnyn_Lab2_PurnynState_TO_Lab2_Purnyn_Proxy_Lab2_PurnynState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
